name: Run Cypress tests on QA

on:
  repository_dispatch:
    types: [run-qa-tests]

  workflow_dispatch:
    inputs:
      browser:
        description: "Selecciona el navegador para ejecutar las pruebas"
        required: false
        default: "chrome"
        type: choice
        options:
          - chrome
          - edge
          - firefox
          - all

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: ${{ fromJson(
          github.event_name == 'repository_dispatch' || github.event.inputs.browser == 'all'
          && '[
            {"browser": "chrome"},
            {"browser": "edge"},
            {"browser": "firefox"}
          ]'
          || format('[{{"browser": "{0}"}}]', github.event.inputs.browser)
        ) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Cypress tests on ${{ matrix.browser }}
        uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}